- id: ldr21_2013-04-28-18-39-05
  desc: non ricord, probabilmente non usare
  code: 
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag":  "${YC2013WS}/../00-ldr21-logs/ldr21_2013-04-28-18-39-05.bag"
    annotations: 
      robot: &ldr21
        name: ldr21
        shape: nominal
        profile: nominal
      motion: 
        agent: servo
      environment: &env
        name: corner1
        config: none
      events:
        disturbances: []
      notes: | 
        none



- id: ldr21_2013-04-28-21-24-29
  desc: Servo experiments in the corner
  code: 
  - rosstream2boot.ExpLogFromYaml
  - files:
      "file:bag":  "${YC2013WS}/../00-ldr21-logs/ldr21_2013-04-28-21-24-29.bag"
    annotations: 
      robot: *ldr21
      environment: *env
      motion: 
        agent: servo
      events:
        disturbances: []
      notes: | 
          Servo experiments with exp18_fast.launch
          
          Works well --- emergent behavior



- id: ldr21_2013-04-28-21-35-34
  desc: Servo experiments in the middle
  code: 
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag":  "${YC2013WS}/../00-ldr21-logs/ldr21_2013-04-28-21-35-34.bag"
      annotations: 
        robot: *ldr21
        environment: *env
        motion: 
          agent: servo
        events:
          disturbances: []
        notes: | 
            Servo experiments with exp18_fast.launch
            Robot acts weirdly -- are batteries off?

