
- id: youbot_servo_ldr_2013-05-02-17-13-37
  desc:  "Youbot 'chicken' behavior. (2)"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": "${DATASETS}/01-youbot-ros-logs-good/youbot_servo_ldr_2013-05-02-17-13-37.bag"
      annotations:
        robot: &unicornB_base1
          name: unicorn
          shape: unicornB
          profile: b3_back2
        motion:
          agent: diffeo_servo  
        environment: &other_corner
          name: vehicles_lab
          config: other_corn
        events:
          disturbances: []
        notes: | 
         has camera: 2013-05-02 16:14:11.mov
         recorded uncompressed camera :/
         dp_unicornB
         unicornA_cr_col160
         youbot_b3_back2

- id: youbot_servo_ldr_2013-05-02-16-55-39
  desc:  "Youbot 'chicken' behavior (1)."
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": "${DATASETS}/01-youbot-ros-logs-good/youbot_servo_ldr_2013-05-02-16-55-39.bag"
      annotations:
        robot: *unicornB_base1
        motion:
          agent: diffeo_servo  
        environment: *other_corner
        events:
          disturbances: []
        notes: | 
         recorded uncompressed camera :/
         has camera 2013-05-02 15:56:20.mov
         the other is better   


- id: youbot_servo_ac_2013-05-02-21-59-37
  desc:  "Looking at Andrea"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": "${DATASETS}/01-youbot-ros-logs-good/youbot_servo_ac_2013-05-02-21-59-37.bag"
      annotations:
        robot: *unicornB_base1
        motion:
          agent: diffeo_servo  
        environment: *other_corner
        events:
          disturbances: []
        notes: | 
         movie: 2013-05-02 20:59:57
         recorded uncompressed camera :/


- id: youbot_servo_cam_2013-05-02-22-11-45
  desc:  "Looking at Andrea with camera in hand"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": "${DATASETS}/01-youbot-ros-logs-good/youbot_servo_cam_2013-05-02-22-11-45.bag"
      annotations:
        robot: *unicornB_base1
        motion:
          agent: diffeo_servo  
        environment: *other_corner
        events:
          disturbances: []
        notes: | 
          movie: 2013-05-02 21:15:11
         recorded uncompressed camera :/

      